### PR TITLE
DOCSINFRA-82 integrate Promote stage into primary pipeline

### PR DESCRIPTION
**Pull request by mojavelinux**
- by default, the pipeline will run using the "build" flow
- the "build" flow will build and publish if the branch is master
- when the "promote only" flow is selected, the build and publish stages are skipped, and the promote stage added
- when the "build and promote" flow is selected, all the stages are run
- the build, publish, and promote stages are never run if the branch is not master
- only sync to s3 when publishing on Sunday
- resolve the CloudFront distribution ID automatically from the internal domain name
- better organize pipeline script
- remove unused nginx config files

### CODE REVIEW

**Comment by mojavelinux** [comment]
@sleslie23 we need a JIRA issue for this task.

**Comment by mojavelinux** [comment]
@sleslie23 Once you approve and I merge, I'd like to test a production promotion. Let me know if you're at a point where that can happen. It does seem like it will roll out the GDPR banner (unless we pin the UI to an older version).

To promote to production, you'll use "Build with Parameters" in the Jenkins UI. The two options are "promote only" and "build and promote". Hopefully those are self-explanatory.

**Comment by mojavelinux** [comment]
I'm going to hold off removing the MuleSoft-promote organization in Jenkins until the promote stage is integrated into the pipeline for the jp site. That's tomorrow.

**Comment by sleslie23** [comment]
@mojavelinux Is this the same as: 9. Migrate promote job to Promote stage in Japanese docs site build?

**Comment by mojavelinux** [comment]
No, that's the next task. What's the issue number for 8?

**Comment by sleslie23** [comment]
@mojavelinux #8: https://www.mulesoft.org/jira/browse/DOCSINFRA-82

**Pull request merged**
